### ISSUE TITLE
Can't run on Win 7 x64 + Node v0.11.2

### ISSUE THREAD

**Issue by jklemm** [zycbob/node-webkit-sqlite3-windows-demo#1]
Hi, when I try to run on Windows 7 Ultimate x64 + Node v0.11.2

C:......\Desktop\node-webkit\exemplos\node-webkit-sqlite3-windows-demo-master>nwbuild -p win -r .
**Latest Version: v0.11.2
Using v0.11.2
Create cache folder in C:\Users\Jorge\AppData\Roaming\npm\node_modules\node-webkit-builder\cache\0.11.2
Using cache for: win64
Launching App
App exited with code 1**

So, the window show and close, without error messages.
How can I debug? Any help?

**Comment by zycbob** [comment]
I guess the Node module sqlite3 in this demo works only with Node v0.10, then you should use node-webkit v0.8.x,  or try to update the Node module sqlite3 to the latest version.

https://github.com/rogerwang/node-webkit
https://github.com/mapbox/node-sqlite3
